### ISSUE TITLE
Replace Jasmine for mocha/chai/sinon (backend for now)

### ISSUE THREAD

**Issue by pameck** [rabblerouser/rabblerouser-core-fork#18]

**Comment by pameck** [comment]
- [ ] Add a global file to avoid repetitive requires in specs (add it to the task definition)
- [ ] rename all temp things
- [ ] remove jasmine.json (the frontend does not need it)
- [ ] create helper for cleaning up the db
- [ ] change mocha reporter
- [ ] the new test task takes ages to run (the compiler maybe?)

**Comment by camjackson** [comment]
This issue was moved to rabblerouser/rabblerouser-core#19
